version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digikala_app:latest
    container_name: digikala_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
    networks:
      - diginet
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=digikala
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis

  nginx:
    image: nginx:stable-alpine
    container_name: digikala_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - diginet

  mysql:
    image: mysql:8.0
    container_name: digikala_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: digikala
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - diginet

  redis:
    image: redis:7-alpine
    container_name: digikala_redis
    ports:
      - "6379:6379"
    networks:
      - diginet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: digikala_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - diginet

volumes:
  dbdata:

networks:
  diginet:
    driver: bridge
